export const JuksData: {
  [key: string]: { name: string; color: string; types: string[] };
} = {
  tr: {
    name: "trend",
    color: "#43EC7C",
    types: [
      "Future Fusion",
      "3D Hyper-Surrealism",
      "Bento Box Grids",
      "Cluttercore",
      "Inflatable 3D",
      "Digital Destruction",
      "Freehand Revival",
      "Anime Bold",
      "Garden Cutouts",
      "Graphic Graffiti",
      "Retro Pixels",
      "Inclusive Visuals",
      "Scrapbooking",
      "Heatmapping",
      "Maximalism",
      "High Contrast",
      "Accessible Colors",
      "Nature-Inspired ",
      "Peached Out",
    ],
  },
  tx: {
    name: "textures",
    color: "#FF63D3",
    types: [
      "Natural ",
      "Geometric ",
      "Grunge ",
      "Abstract ",
      "Watercolor ",
      "Marble ",
      "Wood ",
      "Metal ",
      "Fabric ",
      "Paper ",
      "Stone ",
      "Leather ",
      "Concrete ",
      "Rustic ",
      "Distressed ",
      "Glitter ",
      "Bokeh ",
      "Vintage ",
      "Retro ",
      "Grunge ",
      "Hand-drawn ",
      "Pattern ",
      "Digital ",
      "Photographic ",
      "3D ",
    ],
  },
  pl: {
    name: "palette",
    color: "#7D7BFF",
    types: [
      "Monochromatic",
      "Analogous",
      "Complementary",
      "Triadic",
      "Tetradic",
      "Split Complementary",
      "Double Complementary",
      "Neutral",
      "Pastel",
      "Vibrant",
      "Earthy",
      "Moody",
      "Retro",
      "Neon",
      "Gradient",
      "Minimalist",
      "Nature-Inspired",
      "Seasonal",
      "Cultural",
      "Branded",
      "Accessibility-Focused",
    ],
  },
  tp: {
    name: "typography",
    color: "#FFDA7B",
    types: [
      "Serif",
      "Sans Serif",
      "Slab Serif",
      "Script",
      "Blackletter",
      "Monospace",
      "Display",
      "Handwritten",
      "Decorative",
      "Grotesque",
      "Neo-Grotesque",
      "Geometric",
      "Humanist",
      "Transitional",
      "Modern",
      "Postmodern",
      "Pixel",
      "Retro",
      "Grunge",
      "Minimalist",
      "Organic",
      "Experimental",
      "Variable",
      "Web-Safe",
    ],
  },
  il: {
    name: "illustration",
    color: "#43ECE2",
    types: [
      "Flat Illustration",
      "Line Art",
      "Minimalism",
      "Black and White",
      "Geometric",
      "Watercolor",
      "Digital Painting",
      "Cartoon",
      "Anime",
      "Character Design",
      "Surreal",
      "Abstract",
      "Textured",
      "Hand-drawn",
      "Vector",
      "3D Illustration",
      "Isometric",
      "Cutout",
      "Collage",
      "Pop Art",
      "Retro",
      "Vintage",
      "Grunge",
      "Experimental",
      "Children's Book",
      "Editorial",
      "Infographic",
      "Scientific",
      "Technical",
      "Fashion",
      "Product",
      "Landscape",
      "Portrait",
      "Conceptual",
      "Storytelling",
    ],
  },
  ob: {
    name: "object",
    color: "#696969",
    types: [
      "Old keys",
      "Rusty gears",
      "Colorful buttons",
      "Vintage postcards",
      "Weathered books",
      "Dried flowers",
      "Seashells",
      "Feathers",
      "Ribbons",
      "Twine",
      "Cork",
      "Wire",
      "Wooden blocks",
      "Colored pencils",
      "Paintbrushes",
      "Scrap fabric",
      "Magazine cutouts",
      "Poster fragments",
      "Broken pottery",
      "Glass shards",
      "Wire mesh",
      "Rusty nails",
      "Bottle caps",
      "Playing cards",
      "Stamps",
      "Map pieces",
      "Metallic beads",
      "Crystals",
      "Stones",
      "Sand",
      "Leaves",
      "Twigs",
      "Seeds",
      "Fruits",
      "Vegetables",
      "Spices",
      "Coffee beans",
      "Fabric scraps",
      "Yarn",
      "Buttons",
      "Ribbons",
      "Lace",
      "Thread",
      "Wire",
      "Foam",
      "Cardboard",
      "Wood",
      "Metal",
      "Plastic",
      "Glass",
      "Mirrors",
      "Lightbulbs",
      "Candles",
      "LED lights",
      "Wires",
      "Batteries",
      "Circuit boards",
      "Clocks",
      "Typewriters",
      "Cameras",
      "Musical instruments",
      "Toys",
      "Tools",
      "Kitchen utensils",
      "Sports equipment",
    ],
  },
  fx: {
    name: "effect",
    color: "#EC9443",
    types: [
      "Drop shadows",
      "Inner shadows",
      "Outer glows",
      "Inner glows",
      "Bevel and emboss",
      "Gradients",
      "Color overlays",
      "Pattern overlays",
      "Strokes",
      "Blurs",
      "Sharpen",
      "Noise",
      "Pixelate",
      "Distortion",
      "Liquify",
      "Glass",
      "Neon",
      "Chrome",
      "Metallic",
      "Plastic",
      "Halftone",
      "Retro",
      "Vintage",
      "Glitch",
      "3D transforms",
      "Blending modes",
      "Smart filters",
      "Photo filters",
    ],
  },
  lt: {
    name: "lighting",
    color: "#FFFFFF",
    types: [
      "Natural Light",
      "Studio Light",
      "Stage Light",
      "Ambient Light",
      "Directional Light",
      "Point Light",
      "Spotlight",
      "Backlight",
      "Rim Light",
      "Glow",
      "Neon",
      "Gradient Light",
      "Lens Flare",
      "Bokeh",
      "Vignette",
      "Long Shadow",
      "Color Overlay",
      "Texture Overlay",
      "Double Exposure",
      "Neon Glow",
      "Glitch",
      "Holographic",
      "3D Lighting",
    ],
  },
  el: {
    name: "elements",
    color: "#FF6363",
    types: [
      "Stickers",
      "Tapes",
      "Washi Tape",
      "Stamps",
      "Brush Strokes",
      "Doodles",
      "Illustrations",
      "Hand-drawn Elements",
      "Photo Overlays",
      "Textures",
      "Patterns",
      "Gradients",
      "Drop Shadows",
      "Outlines",
      "Neon Effects",
      "Glitch Effects",
      "Animated Elements",
      "Interactive Elements",
      "Borders",
      "Frames",
      "Callouts",
      "Arrows",
      "Ribbons",
      "Badges",
      "Paper Clips",
      "Push Pins",
      "Thumbtacks",
      "Paper Tears",
      "Folds",
      "Crinkles",
      "Stains",
      "Watercolor Splashes",
      "Grunge Elements",
    ],
  },
  tg: {
    name: "targets",
    color: "#C2EB6C",
    types: [
      "Desktop",
      "Tablet",
      "Mobile",
      "Smartwatch",
      "TV",
      "Digital Signage",
      "Virtual Reality (VR)",
      "Augmented Reality (AR)",
      "Mixed Reality (MR)",
      "Print",
      "Web",
      "App",
      "Game",
      "Interactive Experience",
    ],
  },
};
