import Head from "next/head";
import Image from "next/image";
import router from "next/router";
import Button from "../src/components/common/form/button";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-screen flex flex-col items-center justify-center">
        <Image
          src="/svgs/logo.svg"
          alt="lendsqr Logo"
          width={175}
          height={36}
        />
        <div className="w-40">
          <Button
            onClick={() => router.push(`/login`)}
            className="mt-7.5"
            color="primary"
            variant="filled"
          >
            LOG IN
          </Button>
        </div>
      </div>
    </div>
  );
}
